config/routes.rb
Rails.application.routes.draw do
  resources :filecards
  resources :subjects
  resources :users

  root 'filecards#index'
  get  '/login'  => 'sessions#new'
  post '/login'  => 'sessions#create'
  get  '/logout' => 'sessions#destroy'

end

app/models/filecard.rb
class Filecard < ActiveRecord::Base
  belongs_to :subject
  belongs_to :user

  validates_presence_of :question
  validates_presence_of :answer
  validates_presence_of :user
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :filecards

  has_secure_password
  validates_confirmation_of :password
  validates_presence_of :password_confirmation
  validates_presence_of :name
  validates_presence_of :email
  validates_format_of :email,:with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


def current_user
  @current_user = nil
  if session[:user_id]
    @current_user ||= User.where(id: session[:user_id]).first 
  end
end
helper_method :current_user



end

app/controllers/filecards_controller.rb
class FilecardsController < ApplicationController
  before_action :set_filecard, only: [:show, :edit, :update, :destroy]

  # GET /filecards
  # GET /filecards.json
  def index
    @filecards = Filecard.all
  end

  # GET /filecards/1
  # GET /filecards/1.json
  def show
  end

  # GET /filecards/new
  def new
    @filecard = Filecard.new
  end

  # GET /filecards/1/edit
  def edit
  end

  # POST /filecards
  # POST /filecards.json
  def create
    @filecard = Filecard.new(filecard_params)

    respond_to do |format|
      if @filecard.save
        format.html { redirect_to @filecard, notice: 'Filecard was successfully created.' }
        format.json { render :show, status: :created, location: @filecard }
      else
        format.html { render :new }
        format.json { render json: @filecard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filecards/1
  # PATCH/PUT /filecards/1.json
  def update
    respond_to do |format|
      if @filecard.update(filecard_params)
        format.html { redirect_to @filecard, notice: 'Filecard was successfully updated.' }
        format.json { render :show, status: :ok, location: @filecard }
      else
        format.html { render :edit }
        format.json { render json: @filecard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filecards/1
  # DELETE /filecards/1.json
  def destroy
    @filecard.destroy
    respond_to do |format|
      format.html { redirect_to filecards_url, notice: 'Filecard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filecard
      @filecard = Filecard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def filecard_params
      params.require(:filecard).permit(:question, :answer, :public, :submitDate, :subject_id, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 
  # displays login form
  def new
  end
 
  # checks login data and starts session
  def create
    par = login_params
    user = User.find_by(email: par[:email])
    if user && user.authenticate(par[:password])
      # Save the user id inside the browser cookie. 
      # This is how we keep the user # logged in 
      # when they navigate around our website.
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in'
    else
      redirect_to login_path, alert: 'Log in failed'
    end
  end
 
  # deletes sesssion
  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: 'Logged out'
  end
 
private
 
  def login_params
    params.permit(:email, :password)
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name, :dateCreated, :active, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :email, :regDate, :filecards_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/filecards_helper.rb
module FilecardsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/filecards/_form.html.erb
<%= form_for(@filecard) do |f| %>
  <% if @filecard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@filecard.errors.count, "error") %> prohibited this filecard from being saved:</h2>

      <ul>
      <% @filecard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question %><br>
    <%= f.text_field :question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="field">
    <%= f.label :public %><br>
    <%= f.check_box :public %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.select(:subject_id) do %>
    <%= options_from_collection_for_select(Subject.all, :id, :name) %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.select(:user_id) do %>
      <%= options_from_collection_for_select(User.all, :id, :name) %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/filecards/edit.html.erb
<h1>Editing Filecard</h1>

<%= render 'form' %>

<%= link_to 'Show', @filecard %> |
<%= link_to 'Back', filecards_path %>

app/views/filecards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Filecards</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th>Public</th>
      <th>Submitdate</th>
      <th>Subject</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @filecards.each do |filecard| %>
      <tr>
        <td><%= filecard.question %></td>
        <td><%= filecard.answer %></td>
        <td><%= filecard.public %></td>
        <td><%= filecard.submitDate %></td>
        <td><%= link_to filecard.subject.name, filecard.subject %></td>
        <td><%= link_to filecard.user.name, filecard.user%></td>
        <td><%= link_to 'Show', filecard %></td>
        <td><%= link_to 'Edit', edit_filecard_path(filecard) %></td>
        <td><%= link_to 'Destroy', filecard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Filecard', new_filecard_path %>

app/views/filecards/new.html.erb
<h1>New Filecard</h1>

<%= render 'form' %>

<%= link_to 'Back', filecards_path %>

app/views/filecards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @filecard.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @filecard.answer %>
</p>

<p>
  <strong>Public:</strong>
  <%= @filecard.public %>
</p>

<p>
  <strong>Submitdate:</strong>
  <%= @filecard.submitDate %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @filecard.subject.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @filecard.user.name %>
</p>

<%= link_to 'Edit', edit_filecard_path(@filecard) %> |
<%= link_to 'Back', :back %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>P4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <% if current_user %> 
      Logged in as <%= current_user.name %> 
      <%= link_to "log out", logout_path %>
    <% else %>
      <%= link_to "log in", login_path %>
      | <%= link_to "register", new_user_path %>
    <% end %>
    <h3>Quicklinks:</h3>
    <%= link_to 'Filecards', filecards_path %> | 
    <%= link_to 'Users', users_path %> | 
    <%= link_to 'Subjects', subjects_path %>
  </header>

<%= yield %>

</body>
</html>

app/views/subjects/_form.html.erb
<%= form_for(@subject) do |f| %>
  <% if @subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% @subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dateCreated %><br>
    <%= f.date_select :dateCreated %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form' %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Datecreated</th>
      <th>Active</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= link_to subject.name, subject %></td>
        <td><%= subject.dateCreated %></td>
        <td><%= subject.active %></td>
        <td><%= link_to subject.user.name, subject.user %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form' %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<p>
  <strong>Datecreated:</strong>
  <%= @subject.dateCreated %>
</p>

<p>
  <strong>Active:</strong>
  <%= @subject.active %>
</p>

<p>
  <strong>User:</strong>
  <%= @subject.user.name %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', :back %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :regDate %><br>
    <%= f.date_select :regDate %>
  </div>
  <div class="field">
    <%= f.label :filecards_id %><br>
    <%= f.text_field :filecards_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th>Email</th>
      <th>Regdate</th>
      <th>Filecards</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= user.regDate %></td>
        <% if (user.filecards.length == 0) %>
          <td>No Filecards yet!</td>
        <% else %>
          <td>
          <ul>
          <% user.filecards.each do | filecard |%>
            <li><%= link_to filecard.question, filecard %></li>
          <% end %>
          </ul>
          </td>
        <%end %>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Regdate:</strong>
  <%= @user.regDate %>
</p>


<% if (@user.filecards.length != 0) %>
  <strong>Filecards:</strong>
  <ul>
  <% @user.filecards.each do | filecard |%>
    <li><%= link_to filecard.question, filecard %></li>
  <% end %>
  </ul>
<%end %>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', :back %>